---
- hosts: localhost
  connection: local

  roles:
    - role: faba.docker
      tags:
        - docker
        - docker-network

  vars:
    # Docker variables
    macvlan_name: Docker
    update_images: "no"
    recreate_container: "no"
    docker_appdata: "/appdata"
    docker_temppath: "/tmp/Docker/"

    container_name:
    container_image:
    container_port:
    container_url: "{{ container_name }}.fab-it.biz"
    container_external: false
    container_volumes:
      - "{{ docker_appdata }}/{{ container_name }}:/config"

    container_env:

    netbox_url: "netbox.fab-it.biz"
    traefik_config: "{{ docker_appdata }}/traefik/config"
    pihole_config: "{{ docker_appdata }}//pihole/dnsmasq.d"
    proxy_url: "treafik.fab-it.biz"

  tasks:
    - name: "Import sercrets Vault"
      include_vars: "{{ playbook_dir }}/secrets.yml"
      tags:
        - always

    - name: "Add Container to Netbox"
      include_role:
        name: docker-netbox
        apply:
          tags:
            - prestartup
      vars:
        netbox_api: "{{ netbox_apitoken }}"
        # no need to declare only with multiple containers
        # container_name: "{{ container_name }}"
        # container_port: "{{ container_port }}"

    - name: "Create {{ container_name }} folder"
      file:
        state: directory
        path: "{{ volume.split(':')[0] }}"
      loop: "{{ container_volumes }}"
      loop_control:
        loop_var: volume

    # Uncomment if config is used
    # - name: "Create {{ container_name }} Config"
    #   template:
    #     src: "{{ playbook_dir }}/config/{{ container_name }}/{{ container_name }}.yml"
    #     dest: "{{ docker_appdata }}/{{ docker.{{ container_name }}.name }}/{{ container_name }}.yml"
    #     mode: "0644"
    #     owner: root
    #     group: root

    - name: "Create traefik folder"
      file:
        state: directory
        path: "{{ traefik_config }}"
        owner: root
        group: docker
        mode: 0777

    - name: "Create {{ container_name }} traefik config"
      template:
        src: "{{ playbook_dir }}/traefik.yml"
        dest: "{{ traefik_config }}/{{ container_name }}.yml"
        mode: "0664"
        owner: root
        group: docker

    - name: "Create {{ container_name }} tmp folder"
      file:
        path: "{{ docker_temppath }}/{{ container_name }}"
        mode: "777"
        owner: root
        group: root
        state: directory
        recurse: yes

    - name: "Create {{ container_name }} Docker Compose file"
      template:
        src: "{{ playbook_dir }}/docker-compose.yml"
        dest: "{{ docker_temppath }}//{{ container_name }}/docker-compose.yml"
        mode: "0644"
        owner: root
        group: root

    # Uncomment if env file is needed
    # - name: "Create {{ container_name }} env file"
    #   lineinfile:
    #     path: "{{ docker_temppath }}//{{ container_name }}/.env"
    #     mode: "0644"
    #     owner: root
    #     group: root
    #     line: "{{ env }}"
    #     create: yes
    #   loop: "{{ container_env }}"
    #   loop_control:
    #     loop_var: env

    - name: "Start {{ container_name }} container"
      community.docker.docker_compose:
        project_src: "{{ docker_temppath }}//{{ container_name }}"
    #      register: output

    - name: "Get container info from {{ container_name }}"
      community.docker.docker_container_info:
        name: "{{ container_name }}"
      register: containerinfo

    - name: "Set Container Mac on VM Interface"
      netbox.netbox.netbox_vm_interface:
        netbox_url: "http://{{ netbox_url }}"
        netbox_token: "{{ netbox_apitoken }}"
        data:
          virtual_machine: "{{ container_name }}"
          name: GigabitEthernet1
          mac_address: "{{ containerinfo['container']['NetworkSettings']['Networks']['Docker']['MacAddress'] }}"
        state: present
      when: containerinfo['container'] is defined

    - name: "Add external DNS Records"
      uri:
        url: "https://dns.hetzner.com/api/v1/records"
        method: POST
        headers:
          Content-Type: application/json
          Auth-API-Token: "{{ hetzner_apitoken }}"
        body:
          {
            "value": "home.fab-it.biz.",
            "ttl": 86400,
            "type": "CNAME",
            "name": "{{ container_url }}",
            "zone_id": "ouWiSmyvwUeX8eZHdCwf23",
          }
        body_format: json
      register: dnsanswer
      changed_when: dnsanswer.status == 200
      failed_when: dnsanswer.status != 422 and dnsanswer.status != 200
      ignore_errors: yes
      when: "container_external == true "
      tags:
        - dns

    - name: "Add internal DNS Records"
      lineinfile:
        path: "{{ pihole_config }}/05-pihole-custom-cname.conf"
        line: "cname={{ container_url }},{{ proxy_url }}"
      tags:
        - dns

    - name: "Add internal DNS Records"
      uri:
        url: "http://192.168.0.22/control/rewrite/add"
        method: POST
        url_username : "{{ adguard_user }}"
        url_password: "{{ adguard_pw }}"
        force_basic_auth: yes
        headers:
          Content-Type: application/json
        body:
          {
            "domain": "{{ container_url }}",
            "answer": "{{ proxy_url }}"
          }
        body_format: json
      tags:
        - dns
