---
- hosts: localhost
  connection: local

  roles:
    - role: faba.docker
      tags:
        - docker
        - docker-network

  vars:
    # Docker variables
    update_images: "no"
    recreate_container: "no"
    docker_appdata: "/appdata"
    docker_temppath: "/tmp/Docker/"

    container_name:
    container_image:
    container_port:
    container_volumes:
      - "{{ docker_appdata }}/{{ container_name }}:/config"

    container_env:

  tasks:
    - name: "Import sercrets Vault"
      include_vars: "{{ playbook_dir }}/secrets.yml"
      tags:
        - always

    - name: "Add Container to Netbox"
      include_role:
        name: docker-netbox
      vars:
        netbox_api: "{{ netbox_apitoken }}"
        # container_name: "{{ container_name }}"
        # container_port: "{{ container_port }}"

    - name: "Create {{ container_name }} folder"
      file:
        state: directory
        path: "{{ volume }}"
      loop: "{{ container_volumes }}"
      loop_control:
        loop_var: volume

    - name: "Create {{ container_name }} Config"
      template:
        src: "{{ playbook_dir }}/config/{{ container_name }}/{{ container_name }}.yml"
        dest: "{{ docker_appdata }}/{{ docker.{{ container_name }}.name }}/{{ container_name }}.yml"
        mode: "0644"
        owner: root
        group: root

    - name: "Create {{ container_name }} tmp folder"
      file:
        path: "{{ docker_temppath }}/{{ container_name }}"
        mode: "777"
        owner: root
        group: root
        state: directory
        recurse: yes

    - name: "Create {{ container_name }} Docker Compose file"
      template:
        src: "{{ playbook_dir }}/docker-compose.yml"
        dest: "{{ docker_temppath }}//{{ container_name }}/docker-compose.yml"
        mode: "0644"
        owner: root
        group: root

    - name: "Create {{ container_name }} env file"
      lineinfile:
        path: "{{ docker_temppath }}//{{ container_name }}/.env"
        mode: "0644"
        owner: root
        group: root
        line: "{{ env }}"
        create: yes
      loop: "{{ container_env }}"
      loop_control:
        loop_var: env

    - name: "Start {{ container_name }} container"
      community.docker.docker_compose:
        project_src: "{{ docker_temppath }}//{{ container_name }}"
#      register: output