---
- hosts: localhost
  connection: local

  roles:
    - role: faba.docker
      tags:
        - docker
        - docker-network

  vars:
    # Docker variables
    macvlan_name: Docker
    update_images: "no"
    recreate_container: "no"
    docker_appdata: "/appdata"
    docker_temppath: "/tmp/Docker/"

    container_name:
    container_image:
    container_port:
    container_volumes:
      - "{{ docker_appdata }}/{{ container_name }}:/config"

    container_env:

    external: false

    traefik_config: "{{ docker_appdata }}/traefic/config"

  tasks:
    - name: "Import sercrets Vault"
      include_vars: "{{ playbook_dir }}/secrets.yml"
      tags:
        - always

    - name: "Add Container to Netbox"
      include_role:
        name: docker-netbox
        apply:
          tags:
            - prestartup
      vars:
        netbox_api: "{{ netbox_apitoken }}"
        # no need to declare only with multiple containers
        # container_name: "{{ container_name }}"
        # container_port: "{{ container_port }}"

    - name: "Create {{ container_name }} folder"
      file:
        state: directory
        path: "{{ volume.split(':')[0] }}"
      loop: "{{ container_volumes }}"
      loop_control:
        loop_var: volume

    # Uncomment if config is used
    # - name: "Create {{ container_name }} Config"
    #   template:
    #     src: "{{ playbook_dir }}/config/{{ container_name }}/{{ container_name }}.yml"
    #     dest: "{{ docker_appdata }}/{{ docker.{{ container_name }}.name }}/{{ container_name }}.yml"
    #     mode: "0644"
    #     owner: root
    #     group: root

    - name: "Create traefik folder"
      file:
        state: directory
        path: "{{ traefik_config }}"
        owner: root
        group: docker
        mode: 0777

    - name: "Create {{ container_name }} traeffic config"
      template:
        src: "{{ playbook_dir }}/traefik.yml"
        dest: "{{ traefik_config }}/{{ container_name }}.yml"
        mode: "0664"
        owner: root
        group: docker

    - name: "Create {{ container_name }} tmp folder"
      file:
        path: "{{ docker_temppath }}/{{ container_name }}"
        mode: "777"
        owner: root
        group: root
        state: directory
        recurse: yes

    - name: "Create {{ container_name }} Docker Compose file"
      template:
        src: "{{ playbook_dir }}/docker-compose.yml"
        dest: "{{ docker_temppath }}//{{ container_name }}/docker-compose.yml"
        mode: "0644"
        owner: root
        group: root

    # Uncomment if env file is needed
    # - name: "Create {{ container_name }} env file"
    #   lineinfile:
    #     path: "{{ docker_temppath }}//{{ container_name }}/.env"
    #     mode: "0644"
    #     owner: root
    #     group: root
    #     line: "{{ env }}"
    #     create: yes
    #   loop: "{{ container_env }}"
    #   loop_control:
    #     loop_var: env

    - name: "Start {{ container_name }} container"
      community.docker.docker_compose:
        project_src: "{{ docker_temppath }}//{{ container_name }}"
    #      register: output

    - name: "Add Container Infos to Netbox"
      include_role:
        name: docker-netbox
        apply:
          tags:
            - poststartup
      vars:
        netbox_api: "{{ netbox_apitoken }}"
        # container_name: "{{ container_name }}"
        # container_port: "{{ container_port }}"
