networks:
# Macvlan Network
  {{ macvlan_name }}:
    external: true

# Backend Network
#{{ container_name }}:

services:
  {{ container_name }}:
    container_name: "{{ container_name }}"
    image: "{{ container_image }}"
    restart: always
    networks:
      {{ macvlan_name }}:
        ipv4_address: "{{ container.ip }}"
    environment:
      - PUID="{{ container_name }}"
    volumes: {{ docker_volumes }}

# Postgres DB for container
  # postgres:
  #   container_name: "{{ container_name }}-postgres"s
  #   image: "postgres"
  #   restart: always
  #   networks:
  #     {{ container_name }}:
  #   environment:
  #     - TZ="Europe/Vienna"
  #     - PGDATA="/var/lib/postgresql/data/pgdata"
  #     - POSTGRES_DB="{{ container_name }}"
  #     - POSTGRES_USER="{{ container_name }}"
  #     - POSTGRES_PASSWORD="{{ postgres_mealie_pwd }}"
  #   volumes:
  #     - "{{ docker_appdata }}/{{ container_name }}-postgres/:/var/lib/postgresql/data"